### ISSUE TITLE
Functions in python should be lower case

### ISSUE THREAD

**Issue by russellballestrini** [dustinkirkland/python-petname#3]
This isn't really a bug but in python function names should be lowercase while class names should be title case.

**Comment by dustinkirkland** [comment]
Cool.  Thanks.  Can you send me a pull request?

Dustin Kirkland
Ubuntu Product & Strategy
Canonical, Ltd.

**Comment by rbanffy** [comment]
Should this be marked `wontfix` or would a PR that only addresses the function names and not the PEP-8 recommendations be considered for inclusion?

**Comment by russellballestrini** [comment]
I wasn't able to put time into this change.  We could close this issue as "won't fix" in favor of a more broader PEP-8 issue. No issues from me here, it's up to @dustinkirkland of course since this is his fork.

**Comment by dustinkirkland** [comment]
We'd need to coordinate this with the MAAS team, as they use the python-petname library, and we don't want to break the API.

**Comment by nicktimko** [comment]
Lower case names fixed in cdccaa1 for funsies, but project hath decreed tabs, so *c'est la wontfix* I suppose.

**Comment by dustinkirkland** [comment]
:-)  Yeah, sorry.  I happy to take any PEP8 fixes, except:

 - W191 (God made tabs for a reason, code indentation, obviously)
 - E501 (God gave us high def displays for a reason, larger than 80x24
terminals, obviously)



:-Dustin
@dustinkirkland

**Comment by nicktimko** [comment]
Just suggesting that you could close this issue if the fixes to be fixed are fixed and those that won't aren't 😛

**Comment by russellballestrini** [comment]
Thanks friends!

**Comment by rbanffy** [comment]
I can write a fix to the MAAS product. I think I know the parts where it's used and it'd be trivial to get a properly cased version of the method according to its presence. Later we could just remove the check and go for the lower case when the proper version is distributed in Ubuntu.
