### ISSUE TITLE
DRYer bin scripts

### ISSUE THREAD

**Issue by nicktimko** [dustinkirkland/python-petname#8]
I don't know much about Deb packaging (I gave up when trying to package a 3-4 source file C program because it didn't use enough autotools or whatever the guides expected it to...), but why is the `debian/usr/bin/python?-petname` script not just:

     from petname.__main__ import main
     main()

I always seem to get confused between distro Python's `dist-packages` and `site-packages` and when `pip` installs things where they go vs `apt` or whatever...but if in the existing `python?-petname` scripts they are able to `import petname` at all, I think they should be able to just import the main function and call that.

**Comment by dustinkirkland** [comment]
Yeah, you're right :-)  Nice catch.  Fixed in 2.2.
